### ISSUE TITLE
Move to JavaFX

### ISSUE THREAD

**Issue by vishal-reddy** [crosswire/jsword#102]
Could there be any push to move to JavaFX? For a better looking and maintainable GUI?

**Comment by dmsmith** [comment]
JSword has no GUI code at all. Each front-end (e.g. Bible Desktop [Swing], Alkitab [NetBeans], STEP [HTML], AndBible [Android]) provides its own GUI. I'd welcome help with Bible Desktop. Especially starting with replacing its HTML viewer with the JavaFX web browser.

I'm closing this as not applicable to JSword.
