### ISSUE TITLE
Support for ztext4

### ISSUE THREAD

**Issue by DavidHaslam** [crosswire/jsword#105]
The RusCARS modules recently submitted to CroosWire have lengthy introductions. 

They are configured to use ztext4. 

When will JSword support this?

**Comment by dmsmith** [comment]
I’m testing the change before checking it in.

**Comment by mjdenham** [comment]
Hi David,

I am sure you already realise this, but could I emphasise that if any zText4 modules are deployed to a repository the whole repository (not just that module) becomes inaccessible to JSword apps, so it would be good if you could allow us some time to upgrade JSword and roll out our apps to users before deploying any zText4 modules.

Martin

**Comment by dmsmith** [comment]
Sounds like a bug. A bad module shouldn't affect but that module. 

Cent from my fone so theer mite be tipos. ;)
