### ISSUE TITLE
Book.getGlobalKeyList().iterator() misses last verse(s) of testament

### ISSUE THREAD

**Issue by schierlm** [crosswire/jsword#91]
Hello,

when using Book.getGlobalKeyList().iterator to iterate over all verses of the KJV bible, it misses Malachi 4:6 and Revelation 22:20 and Revelation 22:21. So, the last verse of OT and the last two verses of NT are missing. When explicitly creating Verse objects and calling Book.contains(), it tells me that these verses are there, though.

Happens for other bibles/versifications as well.

Probably some index off-by-one in the Versifications modules somewhere.

Tested in latest commit (748341fc90e253d9fcd866f260cc9c0e4af65f00)

**Comment by dmsmith** [comment]
Many thanks for reporting this. And for your contributions at github.

Hope to be able to look at this soon.

In Him,
	DM

**Comment by schierlm** [comment]
Did you find time to have a look at this? It seems to me (empirically) that it works if you add 1 to the expressions in https://github.com/crosswire/jsword/blob/master/src/main/java/org/crosswire/jsword/book/sword/ZVerseBackend.java#L231 and https://github.com/crosswire/jsword/blob/master/src/main/java/org/crosswire/jsword/versification/Versification.java#L879, but not sure if it is all places to fix and/or other places need adjusting when using different API calls...

**Comment by schierlm** [comment]
Any updates on this (or any workarounds)? This is still broken in the latest version (1983dc1bd39d735a28accadbe282f4a043b225a9)

**Comment by dmsmith** [comment]
Fixed. The problem was within the raw and compressed backend for Bibles in the getGlobalKeyList.
The index 0 was not being counted as a verse, yet it is in the index file. Further, entrySize * maxIndex was wrong. It should have been entrySize * maxCount, because there is one entry per verse, including the skipped entry at the beginning of the index.

**Comment by schierlm** [comment]
Fixed in which commit? I'm still seeing this when trying to iterate over KJV module with jsword revision dbd5f3d30f28acd353f6437ce02488d169174c35

**Comment by schierlm** [comment]
Please ignore my previous message. I somehow managed to have two different versions of jsword on my ClassPath :-(
